#!/usr/bin/env python3
"""run_e2e_loop.py — E2E 자율 루프 통합 진입점.

전 조직 봇이 일일회고/주간회의 채팅에 참여해 보고·조치사항을
GoalTracker에 자동 등록하는 end-to-end 시나리오를 실행한다.

사용 예:
    # 일일회고 시나리오 실행 (dry-run)
    ./.venv/bin/python run_e2e_loop.py --type daily_retro --dry-run

    # 주간회의 시나리오 실행 (실제 GoalTracker 연동)
    ENABLE_GOAL_TRACKER=1 ./.venv/bin/python run_e2e_loop.py --type weekly_meeting

    # 커스텀 보고서 파일 지정
    ./.venv/bin/python run_e2e_loop.py --type daily_retro --report docs/retros/2026-03-25.md

실행 흐름:
    1. 환경 설정 로드 (.env / ~/.ai-org/config.yaml)
    2. GoalTrackerClient 초기화 (ENABLE_GOAL_TRACKER에 따라 tracker 주입 여부 결정)
    3. MultibotMeetingHandler 초기화
    4. handle() 실행 — 봇 보고 수집 → GoalTracker 등록 → 루프 실행
    5. 결과 출력 (states_visited, dispatched_count)
"""
from __future__ import annotations

import argparse
import asyncio
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent
sys.path.insert(0, str(PROJECT_ROOT))


# ── 환경 로드 ─────────────────────────────────────────────────────────────────

def _load_env() -> None:
    for env_path in (Path.home() / ".ai-org" / "config.yaml", PROJECT_ROOT / ".env"):
        if not env_path.exists():
            continue
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                os.environ.setdefault(k.strip(), v.strip())


_load_env()

ENABLE_GOAL_TRACKER = os.environ.get("ENABLE_GOAL_TRACKER", "0") == "1"
GROUP_CHAT_ID = int(os.environ.get("TELEGRAM_GROUP_CHAT_ID", "0"))
PM_BOT_TOKEN = os.environ.get("PM_BOT_TOKEN", "")


# ── 샘플 보고서 ───────────────────────────────────────────────────────────────

_SAMPLE_DAILY_RETRO = """\
# 작업 회고 — {date}

## 오늘 완료된 태스크: 2건

- GoalTracker E2E 자율 루프 구현 (개발실) ✅
- 통합 테스트 코드 작성 (개발실) ✅

## 실패 태스크: 0건

## 조치사항:

- [ ] E2E 테스트 커버리지 100% 달성 담당: 개발실
- [ ] AUTONOMOUS_LOOP.md 문서 작성 담당: 개발실

---
*자동 생성: {now}*
"""

_SAMPLE_WEEKLY_MEETING = """\
# 주간회의 — {date}

## 참석 부서
- 🔧 개발실
- ⚙️ 운영실

## 🔧 개발실 보고
GoalTracker 자율 루프 구현 완료 (idle→evaluate→replan→dispatch).
다음 주: E2E 테스트 100% 커버리지 달성.

## 조치사항:

- [ ] 자율 루프 프로덕션 배포 담당: 운영실 마감: {date}
- [ ] E2E 테스트 전체 통과 확인 담당: 개발실

---
*Generated by run_e2e_loop.py*
"""


# ── 전송 함수 ─────────────────────────────────────────────────────────────────

async def _make_send_func():
    """Telegram 전송 함수 생성 (봇 토큰 있으면 실제, 없으면 noop)."""
    if not PM_BOT_TOKEN:
        async def _noop_send(chat_id: int, text: str) -> None:
            print(f"[SEND → {chat_id}] {text[:80]}")
        return _noop_send

    try:
        from telegram import Bot

        from core.telegram_formatting import markdown_to_html

        async def _real_send(chat_id: int, text: str) -> None:
            try:
                async with Bot(token=PM_BOT_TOKEN) as b:
                    await b.send_message(
                        chat_id=chat_id,
                        text=markdown_to_html(text),
                        parse_mode="HTML",
                    )
            except Exception as e:
                print(f"[SEND 실패] {e}")

        return _real_send
    except ImportError:
        async def _fallback_send(chat_id: int, text: str) -> None:
            print(f"[SEND → {chat_id}] {text[:80]}")
        return _fallback_send


# ── GoalTracker 초기화 ────────────────────────────────────────────────────────

async def _make_goal_tracker():
    """GoalTracker 인스턴스 생성 (ENABLE_GOAL_TRACKER=1 필요)."""
    if not ENABLE_GOAL_TRACKER:
        print("[E2E] ENABLE_GOAL_TRACKER=0 — dry-run 모드")
        return None

    try:
        from pathlib import Path as _Path

        from core.claim_manager import ClaimManager
        from core.context_db import ContextDB
        from core.goal_tracker import GoalTracker
        from core.memory_manager import MemoryManager
        from core.pm_orchestrator import PMOrchestrator
        from core.task_graph import TaskGraph

        db_path = _Path(os.environ.get("CONTEXT_DB_PATH", "~/.ai-org/context.db")).expanduser()
        db = ContextDB(db_path)
        await db.initialize()

        send_func = await _make_send_func()

        async def _telegram_send(chat_id: int, text: str, **kwargs) -> None:
            await send_func(chat_id, text)

        orch = PMOrchestrator(
            context_db=db,
            task_graph=TaskGraph(db),
            claim_manager=ClaimManager(),
            memory=MemoryManager("pm"),
            org_id="pm",
            telegram_send_func=_telegram_send,
        )
        tracker = GoalTracker(
            context_db=db,
            orchestrator=orch,
            telegram_send_func=_telegram_send,
            org_id="pm",
        )
        print("[E2E] GoalTracker 초기화 완료")
        return tracker
    except Exception as e:
        print(f"[E2E] GoalTracker 초기화 실패 (dry-run 전환): {e}")
        return None


# ── 봇 보고 요청 함수 ─────────────────────────────────────────────────────────

async def _simulate_bot_report(org_id: str, chat_id: int, meeting_type: str) -> str:
    """E2E 테스트용 봇 보고 시뮬레이션 (실제 봇 없이 고정 응답)."""
    _reports = {
        "aiorg_engineering_bot": "개발실 보고: 자율 루프 구현 완료. 다음 주 E2E 테스트 완성 예정.",
        "aiorg_ops_bot":         "운영실 보고: 시스템 안정. 배포 파이프라인 정상.",
        "aiorg_design_bot":      "디자인실 보고: UI 컴포넌트 검토 완료.",
        "aiorg_product_bot":     "기획실 보고: Q2 PRD 초안 작성 중.",
        "aiorg_growth_bot":      "성장실 보고: MAU +12%. 주요 지표 양호.",
        "aiorg_research_bot":    "리서치실 보고: 경쟁사 분석 3건 완료.",
    }
    await asyncio.sleep(0.1)  # 실제 봇 응답 지연 시뮬레이션
    return _reports.get(org_id, f"[{org_id}] 보고 내용 없음")


# ── 메인 실행 ─────────────────────────────────────────────────────────────────

async def run_e2e_scenario(
    meeting_type: str,
    report_file: str | None,
    dry_run: bool,
    chat_id: int,
) -> None:
    """E2E 자율 루프 시나리오 실행."""
    from goal_tracker.goal_tracker_client import GoalTrackerClient
    from goal_tracker.multibot_meeting_handler import MultibotMeetingHandler

    now = datetime.now(timezone.utc)
    date_str = now.strftime("%Y-%m-%d")
    print(f"\n{'='*60}")
    print("  E2E 자율 루프 시나리오")
    print(f"  유형: {meeting_type}")
    print(f"  날짜: {date_str}")
    print(f"  dry_run: {dry_run or not ENABLE_GOAL_TRACKER}")
    print(f"{'='*60}\n")

    # 보고서 준비
    if report_file and Path(report_file).exists():
        report_text = Path(report_file).read_text(encoding="utf-8")
        print(f"[E2E] 보고서 로드: {report_file} ({len(report_text)}자)")
    elif meeting_type == "weekly_meeting":
        report_text = _SAMPLE_WEEKLY_MEETING.format(date=date_str, now=now.isoformat())
        print("[E2E] 샘플 주간회의 보고서 사용")
    else:
        report_text = _SAMPLE_DAILY_RETRO.format(date=date_str, now=now.isoformat())
        print("[E2E] 샘플 일일회고 보고서 사용")

    # 컴포넌트 초기화
    tracker = None if dry_run else await _make_goal_tracker()
    send_func = await _make_send_func()

    client = GoalTrackerClient(
        goal_tracker=tracker,
        org_id="aiorg_pm_bot",
        chat_id=chat_id or GROUP_CHAT_ID,
        send_func=send_func,
        dry_run=(tracker is None),
    )

    handler = MultibotMeetingHandler(
        client=client,
        send_func=send_func,
        request_bot_report=_simulate_bot_report,
        bot_request_interval=0.5,   # E2E 테스트에서는 짧은 인터벌
        collect_timeout=30.0,
    )

    # 시나리오 실행
    trigger_messages = {
        "daily_retro": "일일회고 시작합니다",
        "weekly_meeting": "주간회의를 시작하겠습니다",
    }
    trigger = trigger_messages.get(meeting_type, meeting_type)

    print(f"[E2E] 핸들러 실행 중... (트리거: '{trigger}')")
    result = await handler.handle(
        message_text=trigger,
        chat_id=chat_id or GROUP_CHAT_ID,
        force=True,  # E2E 실행 시 항상 강제 실행
    )

    # 결과 출력
    print(f"\n{'─'*60}")
    print("  E2E 결과 요약")
    print(f"{'─'*60}")
    print(f"  성공: {result.success}")
    print(f"  회의 유형: {result.meeting_type}")
    print(f"  봇 보고 수: {result.report_count}")
    print(f"  등록된 조치사항: {result.registered_count}")

    if result.register_result:
        rr = result.register_result
        print(f"  파싱된 아이템: {rr.action_items_found}")
        print(f"  루프 상태: {' → '.join(rr.loop_states) if rr.loop_states else 'N/A'}")
        print(f"  배분 완료: {rr.dispatched_count}")

    if result.bot_reports:
        print("\n  봇 보고 상세:")
        for rep in result.bot_reports:
            status = "✅" if rep.success else "❌"
            print(f"    {status} {rep.org_name}: {rep.report_text[:60]}...")

    if result.error:
        print(f"\n  오류: {result.error}")

    print(f"\n[E2E] 완료 — {datetime.now(timezone.utc).isoformat()}")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="E2E 자율 루프 — 전 조직 봇 일일회고/주간회의 GoalTracker 연동 검증"
    )
    parser.add_argument(
        "--type", choices=["daily_retro", "weekly_meeting"],
        default="daily_retro",
        help="회의 유형 (기본: daily_retro)",
    )
    parser.add_argument(
        "--report", type=str, default=None,
        help="보고서 파일 경로 (없으면 샘플 사용)",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="실제 GoalTracker 연동 없이 로그만 출력",
    )
    parser.add_argument(
        "--chat-id", type=int, default=0,
        help="Telegram 채팅방 ID (기본: TELEGRAM_GROUP_CHAT_ID 환경변수)",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    asyncio.run(run_e2e_scenario(
        meeting_type=args.type,
        report_file=args.report,
        dry_run=args.dry_run,
        chat_id=args.chat_id,
    ))
