"""E2E: 자율 루프 idle→evaluate→replan→dispatch 전체 시나리오 검증.

시나리오 커버:
    1. idle 상태에서 루프 트리거 — AutonomousLoopRunner.run_cycle()이 IDLE에서 시작함을 확인
    2. evaluate 결과에 따른 replan 실행 — 미달성 시 REPLAN 전이 확인
    3. dispatch 후 봇 응답 수신 — dispatch_func 호출 및 DispatchRecord 생성 확인
    4. GoalTracker 자동 등록 확인 — register_report()로 조치사항 파싱·등록 검증
    5. 멀티봇 참여 시나리오 — MultibotMeetingHandler 전체 흐름 검증
    6. 중복 등록 방지 — 동일 meeting_id 재처리 시 skipped=True 확인
    7. 빈 보고서 엣지 케이스 — 조치사항 없는 회고 처리 확인
    8. 오류 복구 — dispatch_func 예외 발생 시 루프 오류 복구 검증

모킹 전략:
    - Telegram API: send_func → AsyncMock
    - GoalTracker API: MockGoalTracker (DB 없는 인메모리 구현)
    - 외부 봇 응답: request_bot_report → AsyncMock
"""
from __future__ import annotations

import asyncio
import sys
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from goal_tracker.goal_tracker_client import GoalTrackerClient, ReportRegisterResult
from goal_tracker.loop_runner import AutonomousLoopRunner, LoopRunResult, run_meeting_cycle
from goal_tracker.multibot_meeting_handler import (
    ALL_ORG_BOTS,
    BotReport,
    MultibotMeetingHandler,
    _build_combined_report,
    _detect_type,
)
from goal_tracker.state_machine import (
    EvaluationResult,
    GoalTrackerState,
    GoalTrackerStateMachine,
)

# ══════════════════════════════════════════════════════════════════════════════
# 공통 픽스처
# ══════════════════════════════════════════════════════════════════════════════


@pytest.fixture
def sample_daily_retro() -> str:
    return """\
# 작업 회고 — 2026-03-25

## 오늘 완료된 태스크: 2건

- GoalTracker 상태머신 구현 (개발실) ✅
- E2E 테스트 초안 (개발실) ✅

## 실패 태스크: 1건

- 배포 파이프라인 수정 (운영실) ❌

## 조치사항:

- [ ] 배포 파이프라인 버그 수정 담당: 운영실 긴급
- [ ] GoalTracker E2E 테스트 완성 담당: 개발실
- [ ] API 스펙 확정 담당: 기획실 마감: 2026-03-31

---
*자동 생성: 2026-03-25T14:30:00+00:00*
"""


@pytest.fixture
def sample_weekly_meeting() -> str:
    return """\
# 주간회의 — 2026 W13 (2026-03-25)

## 참석 부서
- 🔧 개발실
- ⚙️ 운영실

## 🔧 개발실 보고
이번 주 GoalTracker 핵심 루프 구현 완료.
다음 주: E2E 테스트 100% 커버리지 달성.

## ⚙️ 운영실 보고
배포 파이프라인 점검 완료.
블로커: CI 빌드 캐시 용량 부족.

## 조치사항:

- [ ] CI 빌드 캐시 용량 확장 담당: 운영실 긴급
- [ ] E2E 테스트 커버리지 보고서 작성 담당: 개발실

---
*Generated by weekly_meeting_multibot.py*
"""


@pytest.fixture
def mock_send() -> AsyncMock:
    return AsyncMock()


@pytest.fixture
def mock_dispatch() -> AsyncMock:
    return AsyncMock()


class MockGoalTracker:
    """DB 없는 인메모리 GoalTracker mock."""

    def __init__(self):
        self._goals: dict[str, dict] = {}
        self._counter = 0
        self.start_goal_calls: list[dict] = []
        self.update_status_calls: list[tuple] = []

    async def start_goal(self, title: str, description: str = "", meta=None, chat_id: int = 0, org_id: str = "") -> str:
        self._counter += 1
        goal_id = f"G-mock-{self._counter:03d}"
        self._goals[goal_id] = {
            "id": goal_id, "title": title, "description": description,
            "status": "active", "chat_id": chat_id, "iteration": 0,
        }
        self.start_goal_calls.append({"title": title, "goal_id": goal_id})
        return goal_id

    async def get_active_goals(self, org_id=None) -> list[dict]:
        return [g for g in self._goals.values() if g["status"] == "active"]

    async def update_goal_status(self, goal_id: str, status: str) -> dict | None:
        self.update_status_calls.append((goal_id, status))
        if goal_id in self._goals:
            self._goals[goal_id]["status"] = status
            return self._goals[goal_id]
        return None

    async def get_goals_by_title(self, title: str) -> list[dict]:
        return [g for g in self._goals.values() if g["title"] == title]

    class _FakeDB:
        async def get_goal(self, goal_id: str):
            return None

        async def update_goal(self, goal_id: str, **kwargs):
            pass

    _db = _FakeDB()

    async def evaluate_progress(self, goal_id: str):
        from core.goal_tracker import GoalStatus
        return GoalStatus(achieved=False, progress_summary="mock 평가", remaining_work="mock 남은 작업")


@pytest.fixture
def mock_tracker() -> MockGoalTracker:
    return MockGoalTracker()


@pytest.fixture
def gt_client(mock_tracker, mock_send) -> GoalTrackerClient:
    return GoalTrackerClient(
        goal_tracker=mock_tracker,
        org_id="aiorg_pm_bot",
        chat_id=-12345,
        send_func=mock_send,
    )


# ══════════════════════════════════════════════════════════════════════════════
# 시나리오 1: idle 상태에서 루프 트리거
# ══════════════════════════════════════════════════════════════════════════════


class TestScenario1IdleTrigger:
    """시나리오 1: idle 상태에서 루프 트리거 — AutonomousLoopRunner."""

    def test_state_machine_starts_in_idle(self):
        """상태머신 초기 상태 확인 — IDLE이어야 함."""
        sm = GoalTrackerStateMachine("G-test-001")
        assert sm.state == GoalTrackerState.IDLE, "초기 상태는 IDLE이어야 함"

    def test_start_evaluate_transitions_to_evaluate(self):
        """IDLE → EVALUATE 전이 성공."""
        sm = GoalTrackerStateMachine("G-test-001")
        result = sm.start_evaluate()
        assert result is True
        assert sm.state == GoalTrackerState.EVALUATE

    def test_cannot_start_evaluate_if_max_iterations_reached(self):
        """최대 반복 도달 시 EVALUATE 진입 불가."""
        sm = GoalTrackerStateMachine("G-test-001", max_iterations=2)
        sm.ctx.iteration = 2  # 최대 반복 도달
        result = sm.start_evaluate()
        assert result is False
        assert sm.state == GoalTrackerState.IDLE

    @pytest.mark.asyncio
    async def test_loop_runner_starts_from_idle(self):
        """AutonomousLoopRunner: idle에서 시작하여 evaluate로 진입."""
        sm = GoalTrackerStateMachine("G-loop-001")
        runner = AutonomousLoopRunner(goal_id="G-loop-001", state_machine=sm)

        assert runner.current_state == GoalTrackerState.IDLE
        result = await runner.run_cycle(registered_ids=["G-pm-001"])
        assert "idle" in result.states_visited
        assert "evaluate" in result.states_visited


# ══════════════════════════════════════════════════════════════════════════════
# 시나리오 2: evaluate 결과에 따른 replan 실행
# ══════════════════════════════════════════════════════════════════════════════


class TestScenario2EvaluateToReplan:
    """시나리오 2: evaluate → replan 전이 검증."""

    def test_evaluate_not_achieved_triggers_replan(self):
        """미달성 시 EVALUATE → REPLAN 전이."""
        sm = GoalTrackerStateMachine("G-test-002")
        sm.start_evaluate()  # → EVALUATE

        eval_result = EvaluationResult(
            achieved=False,
            progress_pct=0.3,
            done_count=1,
            total_count=3,
            remaining_work="2개 태스크 미완료",
        )
        transitioned = sm.start_replan(eval_result)
        assert transitioned is True
        assert sm.state == GoalTrackerState.REPLAN

    def test_evaluate_achieved_returns_to_idle(self):
        """달성 시 EVALUATE → IDLE 복귀."""
        sm = GoalTrackerStateMachine("G-test-002")
        sm.start_evaluate()  # → EVALUATE

        eval_achieved = EvaluationResult(
            achieved=True,
            progress_pct=1.0,
            done_count=3,
            total_count=3,
            confidence=0.95,
        )
        transitioned = sm.start_replan(eval_achieved)
        assert transitioned is False  # 달성됨 → REPLAN 진입 불가
        # IDLE 복귀
        sm.return_to_idle("달성")
        assert sm.state == GoalTrackerState.IDLE

    @pytest.mark.asyncio
    async def test_runner_evaluate_triggers_replan_when_tasks_exist(self):
        """태스크 있을 때 루프 runner가 replan 단계까지 실행."""
        runner = AutonomousLoopRunner(goal_id="G-loop-002")
        result = await runner.run_cycle(registered_ids=["G-pm-001", "G-pm-002"])
        assert "replan" in result.states_visited
        assert len(result.task_ids) == 2

    @pytest.mark.asyncio
    async def test_runner_skips_replan_when_no_tasks(self):
        """태스크 없을 때 루프 runner가 즉시 idle 복귀."""
        runner = AutonomousLoopRunner(goal_id="G-loop-002-empty")
        result = await runner.run_cycle(registered_ids=[])  # 빈 목록
        # achieved=True (아무것도 할 일 없음) → replan 건너뜀
        assert "replan" not in result.states_visited
        assert result.dispatched is False


# ══════════════════════════════════════════════════════════════════════════════
# 시나리오 3: dispatch 후 봇 응답 수신
# ══════════════════════════════════════════════════════════════════════════════


class TestScenario3DispatchBotResponse:
    """시나리오 3: dispatch → 봇 응답 확인."""

    @pytest.mark.asyncio
    async def test_dispatch_func_called_with_task_ids(self, mock_dispatch):
        """dispatch_func이 task_ids를 받아 호출됨."""
        runner = AutonomousLoopRunner(
            goal_id="G-dispatch-001",
            dispatch_func=mock_dispatch,
        )
        task_ids = ["G-pm-001", "G-pm-002", "G-pm-003"]
        result = await runner.run_cycle(registered_ids=task_ids)

        assert result.dispatched is True
        mock_dispatch.assert_called_once_with(task_ids)

    @pytest.mark.asyncio
    async def test_dispatch_records_created(self, mock_dispatch):
        """dispatch 후 DispatchRecord가 생성됨."""
        runner = AutonomousLoopRunner(
            goal_id="G-dispatch-002",
            dispatch_func=mock_dispatch,
        )
        result = await runner.run_cycle(registered_ids=["G-pm-001", "G-pm-002"])

        assert result.dispatched_count == 2
        for rec in result.dispatch_records:
            assert rec.task_id in ["G-pm-001", "G-pm-002"]

    @pytest.mark.asyncio
    async def test_full_state_sequence_after_dispatch(self, mock_dispatch):
        """dispatch 완료 후 idle 복귀 — 전체 상태 순서 확인."""
        runner = AutonomousLoopRunner(
            goal_id="G-dispatch-003",
            dispatch_func=mock_dispatch,
        )
        result = await runner.run_cycle(registered_ids=["G-pm-001"])
        expected = ["idle", "evaluate", "replan", "dispatch", "idle"]
        assert result.states_visited == expected

    @pytest.mark.asyncio
    async def test_on_dispatch_complete_callback_invoked(self, mock_dispatch):
        """on_dispatch_complete 콜백이 dispatch 완료 후 호출됨."""
        callback_result: list[LoopRunResult] = []

        async def my_confirm(res: LoopRunResult):
            callback_result.append(res)

        runner = AutonomousLoopRunner(
            goal_id="G-dispatch-004",
            dispatch_func=mock_dispatch,
        )
        result = await runner.run_cycle(
            registered_ids=["G-pm-001"],
            on_dispatch_complete=my_confirm,
        )
        assert result.dispatched is True
        assert len(callback_result) == 1
        assert callback_result[0].dispatched_count == 1


# ══════════════════════════════════════════════════════════════════════════════
# 시나리오 4: GoalTracker 자동 등록 확인
# ══════════════════════════════════════════════════════════════════════════════


class TestScenario4GoalTrackerRegistration:
    """시나리오 4: GoalTracker 조치사항 자동 등록 E2E."""

    @pytest.mark.asyncio
    async def test_register_report_parses_action_items(
        self, gt_client, mock_tracker, sample_daily_retro
    ):
        """일일회고에서 조치사항 파싱 및 GoalTracker 등록."""
        with patch(
            "goal_tracker.auto_register.auto_register_from_report",
        ) as mock_auto:
            from goal_tracker.auto_register import AutoRegisterResult
            mock_auto.return_value = AutoRegisterResult(
                report_type="daily_retro",
                meeting_type="daily_retro",
                action_items_found=3,
                registered_ids=["G-pm-001", "G-pm-002", "G-pm-003"],
            )
            with patch("goal_tracker.loop_runner.run_meeting_cycle") as mock_loop:
                from goal_tracker.loop_runner import LoopRunResult
                mock_loop_result = LoopRunResult(goal_id="G-daily-2026-03-25")
                mock_loop_result.states_visited = ["idle", "evaluate", "replan", "dispatch", "idle"]
                mock_loop_result.dispatch_records = [MagicMock(), MagicMock(), MagicMock()]
                mock_loop_result.dispatched = True
                mock_loop.return_value = mock_loop_result

                result = await gt_client.register_report(
                    report_text=sample_daily_retro,
                    report_type="daily_retro",
                )

        assert result.action_items_found == 3
        assert result.registered_count == 3
        assert "G-pm-001" in result.registered_ids
        assert result.dispatched_count == 3

    @pytest.mark.asyncio
    async def test_create_goal_stores_in_tracker(self, gt_client, mock_tracker):
        """create_goal()이 GoalTracker.start_goal()을 호출함."""
        result = await gt_client.create_goal(
            title="E2E 자율 루프 구현",
            description="idle→evaluate→replan→dispatch 전체 구현",
        )
        assert result.success is True
        assert result.goal_id.startswith("G-mock-")
        assert len(mock_tracker.start_goal_calls) == 1

    @pytest.mark.asyncio
    async def test_update_goal_status(self, gt_client, mock_tracker):
        """update_goal()이 GoalTracker.update_goal_status()를 호출함."""
        # 먼저 목표 생성
        create = await gt_client.create_goal(title="테스트 목표")
        goal_id = create.goal_id

        # 상태 업데이트
        update = await gt_client.update_goal(goal_id, status="achieved")
        assert update.success is True
        assert mock_tracker._goals[goal_id]["status"] == "achieved"

    @pytest.mark.asyncio
    async def test_get_active_goals_returns_list(self, gt_client, mock_tracker):
        """get_active_goals()가 활성 목표 리스트 반환."""
        await gt_client.create_goal(title="목표 A")
        await gt_client.create_goal(title="목표 B")

        goals = await gt_client.get_active_goals()
        assert len(goals) == 2

    @pytest.mark.asyncio
    async def test_dry_run_mode_no_tracker_calls(self, mock_send):
        """dry_run=True이면 실제 tracker 호출 없음."""
        dry_client = GoalTrackerClient(
            goal_tracker=None,  # tracker 없음
            dry_run=True,
        )
        result = await dry_client.create_goal(title="드라이런 테스트")
        assert result.success is True
        assert "dryrun" in result.goal_id

    @pytest.mark.asyncio
    async def test_weekly_meeting_registration(
        self, gt_client, sample_weekly_meeting
    ):
        """주간회의 조치사항 자동 등록."""
        with patch(
            "goal_tracker.auto_register.auto_register_from_report"
        ) as mock_auto:
            from goal_tracker.auto_register import AutoRegisterResult
            mock_auto.return_value = AutoRegisterResult(
                report_type="weekly_meeting",
                meeting_type="weekly_meeting",
                action_items_found=2,
                registered_ids=["G-weekly-001", "G-weekly-002"],
            )
            with patch("goal_tracker.loop_runner.run_meeting_cycle") as mock_loop:
                from goal_tracker.loop_runner import LoopRunResult
                mock_result = LoopRunResult(goal_id="G-weekly-2026-03-25")
                mock_result.states_visited = ["idle", "evaluate", "replan", "dispatch", "idle"]
                mock_result.dispatch_records = [MagicMock(), MagicMock()]
                mock_result.dispatched = True
                mock_loop.return_value = mock_result

                result = await gt_client.register_report(
                    report_text=sample_weekly_meeting,
                    report_type="weekly_meeting",
                )

        assert result.report_type == "weekly_meeting"
        assert result.action_items_found == 2
        assert result.registered_count == 2


# ══════════════════════════════════════════════════════════════════════════════
# 시나리오 5: 멀티봇 참여 핸들러
# ══════════════════════════════════════════════════════════════════════════════


class TestScenario5MultibotHandler:
    """시나리오 5: MultibotMeetingHandler 전체 플로우."""

    @pytest.fixture
    def bot_reports_mock(self) -> AsyncMock:
        """각 봇이 정해진 보고를 반환하는 mock."""
        reports = {
            "aiorg_engineering_bot": "개발실 보고: GoalTracker 구현 완료.",
            "aiorg_ops_bot": "운영실 보고: 배포 안정. 블로커 없음.",
            "aiorg_design_bot": "디자인실 보고: UI 프로토타입 검토 중.",
            "aiorg_product_bot": "기획실 보고: PRD v2 작성 완료.",
            "aiorg_growth_bot": "성장실 보고: MAU +15%. 광고 성과 양호.",
            "aiorg_research_bot": "리서치실 보고: 경쟁사 분석 3건 완료.",
        }

        async def _mock_request(org_id: str, chat_id: int, meeting_type: str) -> str:
            return reports.get(org_id, f"[{org_id}] 보고 없음")

        return _mock_request

    @pytest.mark.asyncio
    async def test_handle_daily_retro_trigger(
        self, gt_client, mock_send, bot_reports_mock, sample_daily_retro
    ):
        """일일회고 채팅 수신 → 6개 봇 보고 수집 → GoalTracker 등록."""
        handler = MultibotMeetingHandler(
            client=gt_client,
            send_func=mock_send,
            request_bot_report=bot_reports_mock,
            bot_request_interval=0.0,  # 테스트에서 인터벌 0
            collect_timeout=5.0,
        )

        with patch.object(gt_client, "register_report") as mock_register:
            mock_register.return_value = ReportRegisterResult(
                report_type="daily_retro",
                action_items_found=3,
                registered_ids=["G-pm-001", "G-pm-002", "G-pm-003"],
                loop_states=["idle", "evaluate", "replan", "dispatch", "idle"],
                dispatched_count=3,
            )

            result = await handler.handle(
                message_text="일일회고 시작합니다",
                chat_id=-12345,
            )

        assert result.success is True
        assert result.meeting_type == "daily_retro"
        assert result.report_count == 6  # 6개 봇 모두 보고
        assert mock_register.called

    @pytest.mark.asyncio
    async def test_all_bots_report_collected(
        self, gt_client, mock_send, bot_reports_mock
    ):
        """6개 부서 봇이 모두 보고에 참여함."""
        handler = MultibotMeetingHandler(
            client=gt_client,
            send_func=mock_send,
            request_bot_report=bot_reports_mock,
            bot_request_interval=0.0,
        )

        with patch.object(gt_client, "register_report") as mock_register:
            mock_register.return_value = ReportRegisterResult(
                report_type="daily_retro",
                action_items_found=0,
                registered_ids=[],
            )

            result = await handler.handle(
                message_text="일일회고 시작",
                chat_id=-12345,
            )

        assert result.report_count == len(ALL_ORG_BOTS)
        org_ids = {r.org_id for r in result.bot_reports}
        assert org_ids == {b["id"] for b in ALL_ORG_BOTS}

    @pytest.mark.asyncio
    async def test_handle_weekly_meeting_trigger(
        self, gt_client, mock_send, bot_reports_mock
    ):
        """주간회의 트리거 감지 및 처리."""
        handler = MultibotMeetingHandler(
            client=gt_client,
            send_func=mock_send,
            request_bot_report=bot_reports_mock,
            bot_request_interval=0.0,
        )

        with patch.object(gt_client, "register_report") as mock_register:
            mock_register.return_value = ReportRegisterResult(
                report_type="weekly_meeting",
                action_items_found=2,
                registered_ids=["G-weekly-001", "G-weekly-002"],
            )

            result = await handler.handle(
                message_text="주간회의를 시작하겠습니다",
                chat_id=-12345,
            )

        assert result.meeting_type == "weekly_meeting"
        assert result.success is True

    @pytest.mark.asyncio
    async def test_unknown_trigger_returns_error(self, gt_client, mock_send):
        """회의 트리거 없는 메시지는 오류 반환."""
        handler = MultibotMeetingHandler(client=gt_client, send_func=mock_send)
        result = await handler.handle(
            message_text="안녕하세요, 일반 메시지입니다",
            chat_id=-12345,
        )
        assert result.success is False
        assert result.meeting_type == "unknown"


# ══════════════════════════════════════════════════════════════════════════════
# 시나리오 6: 중복 등록 방지
# ══════════════════════════════════════════════════════════════════════════════


class TestScenario6DuplicatePrevention:
    """시나리오 6: 중복 등록 방지."""

    @pytest.mark.asyncio
    async def test_same_meeting_id_skipped(
        self, gt_client, mock_send
    ):
        """동일 날짜 같은 유형 회의는 두 번째 요청 시 skip."""
        handler = MultibotMeetingHandler(
            client=gt_client,
            send_func=mock_send,
            bot_request_interval=0.0,
        )

        async def mock_request(org_id, chat_id, meeting_type):
            return "보고 내용"

        handler._request_bot_report = mock_request

        with patch.object(gt_client, "register_report") as mock_register:
            mock_register.return_value = ReportRegisterResult(
                report_type="daily_retro",
                action_items_found=1,
                registered_ids=["G-pm-001"],
            )

            # 첫 번째 호출
            result1 = await handler.handle(
                message_text="일일회고 시작", chat_id=-12345
            )
            # 두 번째 호출 (같은 날 같은 유형)
            result2 = await handler.handle(
                message_text="일일회고 재실행", chat_id=-12345
            )

        assert result1.success is True
        assert result2.skipped is True

    @pytest.mark.asyncio
    async def test_force_overrides_dedup(self, gt_client, mock_send):
        """force=True이면 중복 방지 무시하고 재실행."""
        handler = MultibotMeetingHandler(
            client=gt_client,
            send_func=mock_send,
            bot_request_interval=0.0,
        )

        async def mock_request(org_id, chat_id, meeting_type):
            return "보고 내용"

        handler._request_bot_report = mock_request

        with patch.object(gt_client, "register_report") as mock_register:
            mock_register.return_value = ReportRegisterResult(
                report_type="daily_retro",
                action_items_found=1,
                registered_ids=["G-pm-001"],
            )

            result1 = await handler.handle(
                message_text="일일회고", chat_id=-12345
            )
            result2 = await handler.handle(
                message_text="일일회고", chat_id=-12345, force=True
            )

        assert result1.success is True
        assert result2.skipped is False  # force=True로 재실행됨

    def test_reset_processed_clears_state(self, gt_client, mock_send):
        """reset_processed() 호출 후 처리 기록 초기화."""
        handler = MultibotMeetingHandler(client=gt_client, send_func=mock_send)
        handler._processed_meetings.add("daily_retro_2026-03-25")
        assert len(handler.processed_meetings) == 1

        handler.reset_processed()
        assert len(handler.processed_meetings) == 0


# ══════════════════════════════════════════════════════════════════════════════
# 시나리오 7: 빈 보고서 엣지 케이스
# ══════════════════════════════════════════════════════════════════════════════


class TestScenario7EdgeCases:
    """시나리오 7: 엣지 케이스."""

    @pytest.mark.asyncio
    async def test_empty_report_no_registration(self, gt_client, mock_send):
        """빈 보고서 → 조치사항 없음 → GoalTracker 등록 0건."""
        with patch(
            "goal_tracker.auto_register.auto_register_from_report"
        ) as mock_auto:
            from goal_tracker.auto_register import AutoRegisterResult
            mock_auto.return_value = AutoRegisterResult(
                report_type="daily_retro",
                meeting_type="daily_retro",
                action_items_found=0,
                registered_ids=[],
            )

            result = await gt_client.register_report(
                report_text="# 회고 — 오늘 특이사항 없음",
                report_type="daily_retro",
                run_loop=False,  # loop 실행 없이 파싱만
            )

        assert result.action_items_found == 0
        assert result.registered_count == 0
        assert result.dispatched_count == 0

    @pytest.mark.asyncio
    async def test_no_tracker_client_returns_error(self, mock_send):
        """goal_tracker 없는 클라이언트 — create_goal 오류 반환."""
        client = GoalTrackerClient(goal_tracker=None)
        result = await client.create_goal(title="테스트")
        assert result.success is False
        assert result.error is not None

    @pytest.mark.asyncio
    async def test_get_active_goals_without_tracker(self):
        """goal_tracker 없으면 빈 리스트 반환."""
        client = GoalTrackerClient(goal_tracker=None)
        goals = await client.get_active_goals()
        assert goals == []

    def test_detect_type_daily_retro(self):
        """일일회고 트리거 패턴 감지."""
        assert _detect_type("일일회고 시작합니다") == "daily_retro"
        assert _detect_type("daily retro time!") == "daily_retro"

    def test_detect_type_weekly_meeting(self):
        """주간회의 트리거 패턴 감지."""
        assert _detect_type("주간회의를 시작하겠습니다") == "weekly_meeting"
        assert _detect_type("weekly meeting begins") == "weekly_meeting"

    def test_detect_type_returns_none_for_unknown(self):
        """알 수 없는 메시지 → None 반환."""
        assert _detect_type("안녕하세요") is None
        assert _detect_type("배포 완료") is None

    def test_build_combined_report_includes_all_bots(self):
        """통합 보고서에 모든 봇 보고 포함."""
        reports = [
            BotReport(org_id="aiorg_engineering_bot", org_name="🔧 개발실", report_text="개발 완료"),
            BotReport(org_id="aiorg_ops_bot", org_name="⚙️ 운영실", report_text="운영 안정"),
        ]
        combined = _build_combined_report(
            meeting_type="daily_retro",
            bot_reports=reports,
            original_text="",
        )
        assert "🔧 개발실" in combined
        assert "⚙️ 운영실" in combined
        assert "개발 완료" in combined
        assert "운영 안정" in combined


# ══════════════════════════════════════════════════════════════════════════════
# 시나리오 8: 오류 복구
# ══════════════════════════════════════════════════════════════════════════════


class TestScenario8ErrorRecovery:
    """시나리오 8: 오류 복구."""

    @pytest.mark.asyncio
    async def test_dispatch_func_error_sets_result_error(self):
        """dispatch_func 예외 시 LoopRunResult.error 설정됨."""

        async def failing_dispatch(task_ids: list[str]) -> None:
            raise RuntimeError("Telegram API down")

        runner = AutonomousLoopRunner(
            goal_id="G-error-001",
            dispatch_func=failing_dispatch,
        )
        result = await runner.run_cycle(registered_ids=["G-pm-001"])
        assert result.error is not None
        assert result.dispatched is False

    @pytest.mark.asyncio
    async def test_state_machine_returns_to_idle_on_error(self):
        """오류 발생 시 상태머신이 IDLE로 복귀."""

        async def failing_dispatch(task_ids: list[str]) -> None:
            raise ConnectionError("Network error")

        sm = GoalTrackerStateMachine("G-error-002")
        runner = AutonomousLoopRunner(
            goal_id="G-error-002",
            state_machine=sm,
            dispatch_func=failing_dispatch,
        )
        result = await runner.run_cycle(registered_ids=["G-pm-001"])
        # 오류 후 IDLE 복귀
        assert sm.state == GoalTrackerState.IDLE
        assert result.error is not None

    @pytest.mark.asyncio
    async def test_bot_timeout_does_not_block_handler(
        self, gt_client, mock_send
    ):
        """개별 봇 타임아웃이 전체 핸들러를 블록하지 않음."""
        timeout_count = 0

        async def slow_request(org_id: str, chat_id: int, meeting_type: str) -> str:
            nonlocal timeout_count
            if org_id == "aiorg_ops_bot":
                await asyncio.sleep(10)  # 매우 느린 봇 시뮬레이션
            return f"[{org_id}] 보고 완료"

        handler = MultibotMeetingHandler(
            client=gt_client,
            send_func=mock_send,
            request_bot_report=slow_request,
            bot_request_interval=0.0,
            collect_timeout=1.0,  # 1초 타임아웃
        )

        with patch.object(gt_client, "register_report") as mock_register:
            mock_register.return_value = ReportRegisterResult(
                report_type="daily_retro",
                action_items_found=0,
                registered_ids=[],
            )

            result = await handler.handle(
                message_text="일일회고 시작", chat_id=-12345
            )

        # 타임아웃한 봇도 포함해 전체 6개 보고 수집됨
        assert result.report_count == 6
        # 타임아웃 봇은 success=False
        ops_report = next(
            (r for r in result.bot_reports if r.org_id == "aiorg_ops_bot"), None
        )
        assert ops_report is not None
        assert ops_report.success is False

    @pytest.mark.asyncio
    async def test_run_meeting_cycle_convenience_function(self, mock_dispatch):
        """run_meeting_cycle() 편의 함수 정상 동작."""
        result = await run_meeting_cycle(
            meeting_type="daily_retro",
            registered_ids=["G-pm-001", "G-pm-002"],
            dispatch_func=mock_dispatch,
        )
        assert result.dispatched is True
        assert result.dispatched_count == 2
        mock_dispatch.assert_called_once_with(["G-pm-001", "G-pm-002"])


# ══════════════════════════════════════════════════════════════════════════════
# 통합 E2E: 전체 파이프라인
# ══════════════════════════════════════════════════════════════════════════════


class TestFullE2EPipeline:
    """전체 E2E 파이프라인: 채팅 수신 → 봇 보고 → 등록 → 루프 → 배분."""

    @pytest.mark.asyncio
    async def test_daily_retro_full_e2e_pipeline(
        self, mock_tracker, mock_send, mock_dispatch, sample_daily_retro
    ):
        """일일회고 채팅 → 봇 보고 수집 → GoalTracker 등록 → 자율 루프 실행."""
        # 1. 클라이언트 및 핸들러 구성
        client = GoalTrackerClient(
            goal_tracker=mock_tracker,
            org_id="aiorg_pm_bot",
            chat_id=-12345,
            send_func=mock_send,
        )

        async def bot_report_func(org_id: str, chat_id: int, meeting_type: str) -> str:
            return f"[{org_id}] 주간 보고 내용 — 정상 운영"

        handler = MultibotMeetingHandler(
            client=client,
            send_func=mock_send,
            request_bot_report=bot_report_func,
            bot_request_interval=0.0,
        )

        # 2. GoalTracker 등록 mock
        with patch(
            "goal_tracker.auto_register.auto_register_from_report"
        ) as mock_auto, patch(
            "goal_tracker.loop_runner.run_meeting_cycle"
        ) as mock_loop:
            from goal_tracker.auto_register import AutoRegisterResult
            from goal_tracker.loop_runner import LoopRunResult

            mock_auto.return_value = AutoRegisterResult(
                report_type="daily_retro",
                meeting_type="daily_retro",
                action_items_found=3,
                registered_ids=["G-pm-001", "G-pm-002", "G-pm-003"],
            )

            loop_res = LoopRunResult(goal_id="G-daily-2026-03-25")
            loop_res.states_visited = ["idle", "evaluate", "replan", "dispatch", "idle"]
            loop_res.dispatch_records = [MagicMock(), MagicMock(), MagicMock()]
            loop_res.dispatched = True
            mock_loop.return_value = loop_res

            # 3. 핸들러 실행
            result = await handler.handle(
                message_text="일일회고 시작합니다",
                chat_id=-12345,
            )

        # 4. 검증
        assert result.success is True
        assert result.meeting_type == "daily_retro"
        assert result.report_count == 6
        assert result.registered_count == 3
        assert result.register_result is not None
        assert result.register_result.dispatched_count == 3

        # 5. 전송 함수 호출 확인
        assert mock_send.call_count >= 2  # 시작 알림 + 완료 알림
